name: Automate Weather Data Process

on:
  schedule:
    - cron: "0 8 * * *"  # Exécution tous les jours à 8h (UTC)
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  automate-process:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collecter les données météo
        run: python fetch_weather_data.py

      - name: Insérer dans SQLite
        run: python insert_to_db.py

      - name: (Optionnel) Lancer Streamlit
        run: streamlit run app.py
